"use client";
import { useEffect, useState } from "react";  // Import useState and useEffect
import localFont from "next/font/local";
import "./globals.css";
import SessionWrapper from "./components/sessionWrapper";
import Head from "next/head";
import styles from './map/map.module.css';
import { IonIcon } from '@ionic/react'; // Correct import for IonIcon
import { logoFacebook, logoTwitter, logoInstagram, logoYoutube } from 'ionicons/icons'; // Correct icon imports
import Image from 'next/image'; // Correct import for Image
import Navbar from "./components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isClient, setIsClient] = useState(false);  // State to track if the component is mounted

  useEffect(() => {
    setIsClient(true);  // Set the state to true once the component has mounted on the client
  }, []);

  return (
    <SessionWrapper>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <html>
        <body>
          <div className={styles.header}>
            <a href="/home" className={styles.imageBox}>
              <Image src="/garden_tech_logo_1.png" alt="PageLogo" width={200} height={200} />
              
              {/* Conditionally render Navbar on the client side */}
              {isClient && <Navbar />}
            </a>
          </div>
          {children}
          <footer className={styles.footer}>
            <div className={styles.footerLinksContainer}>
              <p><a className={styles["underlined-link"]} href="/help">HELP</a></p>
              <p><a className={styles["underlined-link"]} href="/about">ABOUT US</a></p>
              <p><a className={styles["underlined-link"]} href="/map">GARDEN MAP</a></p>
            </div>
            <ul className={styles.socialIcons}>
              <li className={styles.socialIconItem}>
                <a className={styles.socialIconLink} href="https://www.facebook.com/groups/292349064176169/">
                  <IonIcon icon={logoFacebook} />
                </a>
              </li>
              <li className={styles.socialIconItem}>
                <a className={styles.socialIconLink} href="https://www.instagram.com/explore/locations/245775754/ut-dallas-community-garden/">
                  <IonIcon icon={logoInstagram} />
                </a>
              </li>
              <li className={styles.socialIconItem}>
                <a className={styles.socialIconLink} href="https://twitter.com/utdgarden">
                  <IonIcon icon={logoTwitter} />
                </a>
              </li>
              <li className={styles.socialIconItem}>
                <a className={styles.socialIconLink} href="https://www.youtube.com/@OSVUTDallas">
                  <IonIcon icon={logoYoutube} />
                </a>
              </li>
            </ul>
          </footer>
        </body>
      </html>
    </SessionWrapper>
  );
}
